### ISSUE TITLE
桌面日历是否可以增加月份切换功能？

### ISSUE THREAD

**Issue by Sc-Eric-B** [YJammak/Weather#108]
如题，请问大佬，桌面日历是否可以增加往下翻往上翻月份的功能。谢谢

**Comment by YJammak** [comment]
![image](https://github.com/YJammak/Weather/assets/6831200/a672f9b9-c8b5-4f76-bc8f-a140a708544a)
任务栏图标右击菜单里可以上翻下翻月份，日历详情可以弹出日历对话框

**Comment by Sc-Eric-B** [comment]
> ![Snipaste_2024-06-20_12-46-52 （自定义）](https://private-user-images.githubusercontent.com/6831200/341273352-9b50afb1-1960-4f45-9685-f3c10149aa6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjE3OTIsIm5iZiI6MTcxODg2MTQ5MiwicGF0aCI6Ii82ODMxMjAwLzM0MTI3MzM1Mi05YjUwYWZiMS0xOTYwLTRmNDUtOTY4NS1mM2MxMDE0OWFhNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMDUzMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA4YTcwZDNmMWRmZTg4NGVmMmEwZTAyYjhkOWNmMGNkNmFlZDZmYjU1MGE5ZjYyNzUyNDA0MjQyNmIyM2M0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P5T0EA3CLrPpe_1G977RLK6MtufUhNDTHAUqwBRwWdc) **任务栏图标右击菜单里可以上翻下翻月份，日历详情可以弹出日历对话框**

就是请问大佬，桌面日历能不能有这个功能？往下翻几个月可以直接在桌面日历上完成。感谢你回复我

**Comment by YJammak** [comment]
> > ![Snipaste_2024-06-20_12-46-52 （自定义）](https://private-user-images.githubusercontent.com/6831200/341273352-9b50afb1-1960-4f45-9685-f3c10149aa6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjE3OTIsIm5iZiI6MTcxODg2MTQ5MiwicGF0aCI6Ii82ODMxMjAwLzM0MTI3MzM1Mi05YjUwYWZiMS0xOTYwLTRmNDUtOTY4NS1mM2MxMDE0OWFhNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMDUzMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA4YTcwZDNmMWRmZTg4NGVmMmEwZTAyYjhkOWNmMGNkNmFlZDZmYjU1MGE5ZjYyNzUyNDA0MjQyNmIyM2M0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P5T0EA3CLrPpe_1G977RLK6MtufUhNDTHAUqwBRwWdc) **任务栏图标右击菜单里可以上翻下翻月份，日历详情可以弹出日历对话框**
> 
> 就是请问大佬，桌面日历能不能有这个功能？往下翻几个月可以直接在桌面日历上完成。感谢你回复我

桌面日历的初衷是固定在桌面展示的，越少交互越少。目前没有在桌面日历上添加更多交互的打算。如果你感兴趣可以Fork一份代码自己添加相关功能。
