### ISSUE TITLE
桌面日历消失

### ISSUE THREAD

**Issue by Sc-Eric-B** [YJammak/Weather#109]
win11 点击显示桌面后，桌面日历会消失

**Comment by YJammak** [comment]
对的，默认桌面日历本身是一个在桌面图标层的窗口，隐藏桌面图标时会一起隐藏。
可以在任务栏图标菜单里选择“置顶“，桌面日历会重启为普通窗口并浮在所有程序上面，隐藏桌面图标时也不会消失。
至于浮在所有程序上面的特性看你需不需要，不需要的话可以自己先改一下。我目前没有时间修改代码。
