### ISSUE TITLE
设置为最上

### ISSUE THREAD

**Issue by FreeVB** [YJammak/Weather#27]
建立 加一个可以设置为窗口最上层功能。

**Comment by YJammak** [comment]
请查看 #2

**Comment by FreeVB** [comment]
哦，那个关闭了，没看到。

置顶方便查看，毕竟不能我为了看一下天气还要切换到桌面对吧，至少可以弄一个开关，喜欢置顶的就置顶，否则就置底。
我以前实现了，后来下载新代码时直接覆盖了，忘记怎么实现的了。
