### ISSUE TITLE
关于置顶和其他功能建议

### ISSUE THREAD

**Issue by FreeVB** [YJammak/Weather#3]
可能我描述的不对，我的意思是加一个功能设置，可以根据自己需要来设置是置顶还是置底
（置顶是为了可以随时都可以看到相关信息，比如查看时间）
我本来已经实现了，只是还没有加在弹出菜单里面，下载新代码后直接给覆盖了。。。
还有就是主界面最好也能弹出操作菜单。
天气能不能根据显示的信息显示相应图片？比如晴天显示太阳，雨天显示下雨的图片这样。

**Comment by yjk282** [comment]
日历详情窗口添加了置顶按钮
天气是有图片的源码里没有添加，后面我看看怎么上传上去
主界面菜单后面会添加

**Comment by yjk282** [comment]
@FreeVB 

可以下载[天气图片资源](https://github.com/yjk282/Weather/releases/download/v0.1.0/Weathers.zip)到运行目录
然后就可以看到天气图片里

**Comment by FreeVB** [comment]
谢谢你的更新，天气图片果然显示了。

**Comment by YJammak** [comment]
@FreeVB 

不怎么上QQ，有问题你直接提Issues就行。
