### ISSUE TITLE
行政划分变化了（2011年变更）导致程序闪退

### ISSUE THREAD

**Issue by dd-rongfa** [YJammak/Weather#92]
2011年安徽省巢湖市下面的庐江县被划分给安徽省合肥市下面了。
如果地理位置仍选择 安徽省-巢湖市-庐江县，程序会闪退，并且无法再打开。
![日历2](https://github.com/YJammak/Weather/assets/30541098/e5397968-7e17-4530-9a33-2b852ff7f34c)
![日历](https://github.com/YJammak/Weather/assets/30541098/56b6307e-5f8a-4af1-be2e-34e420c8a9b4)

**Comment by YJammak** [comment]
> 2011年安徽省巢湖市下面的庐江县被划分给安徽省合肥市下面了。 如果地理位置仍选择 安徽省-巢湖市-庐江县，程序会闪退，并且无法再打开。 ![日历2](https://private-user-images.githubusercontent.com/30541098/305809526-e5397968-7e17-4530-9a33-2b852ff7f34c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzY2NTEsIm5iZiI6MTcwODMzNjM1MSwicGF0aCI6Ii8zMDU0MTA5OC8zMDU4MDk1MjYtZTUzOTc5NjgtN2UxNy00NTMwLTlhMzMtMmI4NTJmZjdmMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA5NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NTc5ZjcyZTQxNDM1YzY2ZmRkYmVjOWZmYmQxNTFlODM5ZDgwMTdmOGU2NmFmNDkzMGJjNTE0MDUwNGMyZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v8j_f2BrHK2ET7D6f69v5_MENnWJgxmDB-SK-1c4Z2k) ![日历](https://private-user-images.githubusercontent.com/30541098/305809545-56b6307e-5f8a-4af1-be2e-34e420c8a9b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzY2NTEsIm5iZiI6MTcwODMzNjM1MSwicGF0aCI6Ii8zMDU0MTA5OC8zMDU4MDk1NDUtNTZiNjMwN2UtNWY4YS00YWYxLWJlMmUtMzRlNDIwYzhhOWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA5NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZmUzYjI5ZjU1YTkxYzkyM2VkODViNDZjNjFkZDZlNzYyYzM5N2JjOTE5YjhiMzlmN2U1ZDFlOGE1MTFhZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NkmmAWpjxM6IIEBSXfVGhL3v5tsn2DCxbmD-v64Fm2w)

@dd-rongfa  可以打开程序目录下的config.json文件，可以用`101021200`替换`CityKey`字段的值，临时解决无法打开程序的问题，行政划分问题后面进行解决

**Comment by YJammak** [comment]
@dd-rongfa 已修复问题，请查看最新版本

**Comment by dd-rongfa** [comment]
> @dd-rongfa 已修复问题，请查看最新版本

确认问题解决。感谢！
